### ISSUE TITLE
Clear the recently used key from the storage in case of RESET_STACK or reaching last state of the dialog.

### ISSUE THREAD

**Issue by akarsh1995** [Tishka17/aiogram_dialog#106]
In the image shown below the keys contains the data from the previous dialogs' state. Is it possible to evict the keys for which the dialog reached its last state ?

![Screenshot 2021-12-25 at 9 35 18 AM](https://user-images.githubusercontent.com/25827628/147377161-6c95de15-8a11-4e6c-9d75-66feb6224896.png)

**Comment by Tishka17** [comment]
Looks like a bug, it was deisgned to erase all usused contexts from storage.

**Comment by Tishka17** [comment]
@akarsh1995 I have checked redis storage with current version of aiogram (2.18) and removed contexts are also evicted from redis. Please, check version of aiogram you use. Also it is possible, that these keys were created when aiogram was not updated.
