### ISSUE TITLE
Can the first window in a dialog show a user id on one of its widgets?

### ISSUE THREAD

**Issue by boyaryn** [Tishka17/aiogram_dialog#109]
As I see in [subdialog.py](https://github.com/Tishka17/aiogram_dialog/blob/develop/example/subdialog.py), it's possible to get the user id from m.chat.id. But that requires moving from one window in a dialog to another. What if I just created a dialog and the user didn't move between windows?

Thanks in advance!

**Comment by Tishka17** [comment]
1. In window getter you can access current processing event via `dialog_manager.event` it will be Message, Callback or DialogUpdate
2. Other possibility is to do some login in dialogs's `on_start` callback
