### ISSUE TITLE
Есть варианты динамически рендерить кнопки для ScrollingGroup?

### ISSUE THREAD

**Issue by valinorq1** [Tishka17/aiogram_dialog#125]
Я организовал фильтры с помощью чек боксов, радио и подтягиваю данные из бд в зависимости от фильтров(база асинхронная)
И чёт не могу понять, как мне динамически отрендерить n-кнопок в ScrollingGroup с данными которые вернёт дб
Есть варианты как то динамически решить вопрос?
async def get_listing(dialog_manager: DialogManager, **kwargs):
    dialog_data = dialog_manager.current_context().dialog_data

    return {
        "result": dialog_data.get("selected_currency", "Все"),
        "vendor": "Все",
        "selected_hash": dialog_data.get("selected_hash", "Все"),
        "btn": dialog_data.get("btn", 'Ничего') # по факту тут лежит список со строками
    }

`ScrollingGroup(
            Button(Format("{btn}"), id=str("123")),
            id="numbers",
            width=6,
            height=6,
        ),`

**Comment by Tishka17** [comment]
`ScrollingGroup` умеет прокручивать любые инлайн кнопки, каким бы способом они ни создавались. Можно просто взять `Select`/`Radio`/`Multiselect` и положить его в `ScrollingGroup` и он оставит только ту часть, что попала на страницу
