### ISSUE TITLE
Бот реагирует на каждый файл по отдельности

### ISSUE THREAD

**Issue by MyZik** [Tishka17/aiogram_dialog#138]
Всем привет, уже больше недели не могу разобраться c проблемой. Ситуация следующая: бот принимает в диалоге файлы, если всё верно (расширение, размер и т.д.), бот создаёт папку и сохраняет файлы. Если нет - показывает соответствующее сообщение.

Проблема заключается в том, что если отправить боту несколько файлов (по отдельности или альбомом), то бот реагирует на каждый отдельный файл, что очень раздражает. Скриншоты, как это выглядит в боте, прикрепляю ниже.

<img width="448" alt="Bildschirmfoto 2022-04-16 um 23 52 31" src="https://user-images.githubusercontent.com/12817320/163692436-b1c530fd-0ce1-42ff-b07e-8c28284bac62.png">

<img width="448" alt="Bildschirmfoto 2022-04-16 um 23 52 36" src="https://user-images.githubusercontent.com/12817320/163692441-ddd16ab4-d213-4053-9c45-60dd65fceb7d.png">

Можно ли как-то это отключить, или обойти? Спасибо заранее за помощь!

aiogram: v2.20.0
aiogram_dialog: v1.4.1

**Comment by Tishka17** [comment]
При использовании aiogram 2: придумать какую-то middware, которая будет блокировать обработку других событий этого юзера пока не завершится текущее. Например, с помощью asyncio.Lock. Важно эту мидлварь зарегистрировать раньше чем DiagloRegistry

**Comment by Tishka17** [comment]
Для aiogram3 нужно использовать isolate_events.

**Comment by omegastripes** [comment]
> Для aiogram3 нужно использовать isolate_events.

Для тех, кто ищет пример - [вот он](https://github.com/Tishka17/aiogram_dialog/blob/210abeeac180d9af7e8203b3643e12edbf01af52/example/loading.py#L85).
