### ISSUE TITLE
Нужно передать router, чтобы выполнялось всё!

### ISSUE THREAD

**Issue by ddranic** [Tishka17/aiogram_dialog#141]
Пока я не передал router в registry бот повторял тоже сообщение.
![image](https://user-images.githubusercontent.com/78444980/167390999-17a96d8b-e072-4ef9-b9e1-47c71f70dce9.png)

После добавления реагирует.
![image](https://user-images.githubusercontent.com/78444980/167391049-a2c7370b-a691-4f65-9b3a-05f83e6b65ae.png)

**Comment by Tishka17** [comment]
see 2.0.0b8
