### ISSUE TITLE
Bug: Context and stack saving problem

### ISSUE THREAD

**Issue by darksidecat** [Tishka17/aiogram_dialog#155]
There is a problem when the context and the stack are saved separately, in the event of an exception, they may end up in an inconsistent state in the storage.

For example, [here](https://github.com/Tishka17/aiogram_dialog/blob/996a71936f1435d9c02bf3f1fd70872cbb85fc29/aiogram_dialog/manager/manager.py#L132) we save the context but do not save the changed stack.
and in case of an error, for example, in [process_result](https://github.com/Tishka17/aiogram_dialog/blob/e5e947d6890c5b734b20811cd0f6f6e6eb6ef8ee/aiogram_dialog/manager/manager.py#L91) we will get a mismatch between the stack and context data if we use a storage backend with persistent data storage ( not MemoryStorage, since there is no such problem with it due to the fact that it allows us to operate data directly in memory)

[MRE](https://gist.github.com/darksidecat/945e60c62f2622c1b823323798f5fe61)

**Comment by Tishka17** [comment]
Need to check more places like
` _start_normal`:
https://github.com/Tishka17/aiogram_dialog/blob/develop/src/aiogram_dialog/manager/manager.py#L229
