### ISSUE TITLE
How to fix aiogram_dialog.exceptions.UnknownIntent error?

### ISSUE THREAD

**Issue by IrSent** [Tishka17/aiogram_dialog#172]
@Tishka17 Could you elaborate on how to fix "aiogram_dialog.exceptions.UnknownIntent: Context not found for intent id: xxxxx" errors?
Maybe we can have a way of creating this data manually until self healing mechanism is developed?
Thanks in advance.

**Comment by bondarev** [comment]
Same problem

**Comment by Finzky** [comment]
Look into error_handler of this example:  https://github.com/Tishka17/aiogram_dialog/blob/develop/example/simple.py

**Comment by IrSent** [comment]
@Finzky AttributeError: 'Dispatcher' object has no attribute 'errors'

**Comment by Tishka17** [comment]
Examples have been updated to the latest aiogram version.

**Comment by itspheras** [comment]
I get an error after error:

  File ".venv\Lib\site-packages\pydantic\main.py", line 753, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}') from exc
AttributeError: 'ErrorEvent' object has no attribute 'from_user'

in code:

async def on_start(self: Any, manager: DialogManager) -> None:
      telegram_id = manager.event.from_user.id
