### ISSUE TITLE
Edit Dialog Window after MessageInput and not "republish" it

### ISSUE THREAD

**Issue by AlexanderRyzhov** [Tishka17/aiogram_dialog#185]
Dialog windows are normally shown in one chat message by editing this message when user ineracts with it with help of inline buttons.
But after usage of text input with MessageInput widget main dialog window is send as new message, and not edited.
Is there any way to achive such behaviour, when user input is processed and main dialog is edited and not published one more time?

**Comment by AlexanderRyzhov** [comment]
I am not sure, but maybe using TextInput in place of MessageInput would solve my problem? 
Is there any example of TextInput widget usage?

**Comment by Tishka17** [comment]
Yes. You can set `manager.show_mode=ShowMode.EDIT` in you message input callbacle
