### ISSUE TITLE
Some MessageManager methods throws TelegramBadRequest exception

### ISSUE THREAD

**Issue by bondarev** [Tishka17/aiogram_dialog#204]
There is no way to catch exceptions within some of the `MessageManager` methods.

For example, `send_message` can throw the `aiogram.exceptions.TelegramBadRequest` exception. Example: the user banned the bot, no chat with the given id (`Bad Request: chat not found`): 

https://github.com/Tishka17/aiogram_dialog/blob/47936befef1f8c5567a56b297900617e33a874b9/aiogram_dialog/manager/message_manager.py#L207

Perhaps it is worth adding an exception handling, as for safe methods in the same class: https://github.com/Tishka17/aiogram_dialog/blob/47936befef1f8c5567a56b297900617e33a874b9/aiogram_dialog/manager/message_manager.py#L115

**Comment by Tishka17** [comment]
Probably the best way to deal with user bans is to handle them in you error handler. But I will think about it
