### ISSUE TITLE
Scrolling group customization

### ISSUE THREAD

**Issue by Tishka17** [Tishka17/aiogram_dialog#232]
We need some how customize scrolling group panel. Possible options:

1. Locate on top/buttom
2. Different combintaions of buttons:

`[1] [prev] [10] [next] [100]`
same with another text
`[<<] [<] [current] [>] [>>]`
`[1] [9] [10] [11] [100]`

fewer buttons:
`[<] [10] [>]`
`[<] [>]`
`[<<] [<] [>] [>>]`
all buttons for cases when pages <10
`[1] [2] [3] [4] [5] [*6*] [7] [8] [9] [10]`
`[1] [2] [3] [*4*] [5]`
`[*1*] [2]`

Mixed:
`[ << 1 ] [ < 7 ] [ 8 ] [ *9* ] [10  > ]`
`[ <  1 ] [ *2* ] [ 3 ] [ 4 > ] [10 >> ]`

Translation and styling current page should be available

see also: https://habr.com/ru/post/501812/

**Comment by prepwork** [comment]
Very roughly, I imagine it to be something like [this](https://github.com/prepwork/aiogram_dialog/blob/develop/src/aiogram_dialog/widgets/kbd/scrolling_group.py).

It allows to create the following pagers mantioned by you:

`[1] [prev] [10] [next] [100]`
`[<<] [<] [current] [>] [>>]`
`[<] [10] [>]`
`[<] [>]`
`[<<] [<] [>] [>>]`

It would be nice to use `Group` with custom pager, but I don't know how to properly pass `__value__` (it keeps value of `prev_page`, `current_page` etc.) to buttons in a `Group`. Also, which class is it better to inherit from for the `PagerButton` class that I have created?

Here is [an example](https://github.com/prepwork/aiogram_dialog/blob/develop/example/custom_scrolling_group.py).

I would like to hear your proposals and opinion 😀

**Comment by Tishka17** [comment]
https://github.com/Tishka17/aiogram_dialog/blob/develop/example/scrolls.py
