### ISSUE TITLE
Non-working examples.

### ISSUE THREAD

**Issue by PieceOfGood** [Tishka17/aiogram_dialog#233]
For me, this is one of the first experiences and, together with the installation of aiogram, I decided to study your approach to this matter as well. Could you update the folder with examples to their current state. None of them work, but I would like to look at the functionality "in the battle", reducing the time for typing with copy-paste.
Благодарю!
![image](https://user-images.githubusercontent.com/31653906/217041500-02c2da9d-9bc7-4bca-8b17-cde7505d15ef.png)

**Comment by metya** [comment]
It's because examples are from the newest version of the packet from the develop branch. Try switch to the master branch, which is installed from pypi by default.

**Comment by Tishka17** [comment]
Use git tags to switch between versions. Current main version is 2.x and supposed to be used with aiogram v3.x. If you need examples for previous versions - switch branch to master or to a concrete tag

**Comment by PieceOfGood** [comment]
Exactly. Thank you very much!
