### ISSUE TITLE
Fix import of UnknownIntent

### ISSUE THREAD

**Issue by IrSent** [Tishka17/aiogram_dialog#234]
https://github.com/Tishka17/aiogram_dialog/blob/f39fafedcf87792afd11869aba31ea3656274077/example/simple.py#L16

import with error:
from aiogram_dialog.api.exceptions import UnknownIntent
`ModuleNotFoundError: No module named 'aiogram_dialog.api'`

import without error:
from aiogram_dialog.exceptions import UnknownIntent

**Comment by Tishka17** [comment]
probably you are trying to use latest examples with 1.9 version. Take examples from git tag please
