### ISSUE TITLE
aiogram_dialog.exceptions.IncorrectBackgroundError: 

### ISSUE THREAD

**Issue by almaziphone** [Tishka17/aiogram_dialog#235]
aiogram_dialog.exceptions.IncorrectBackgroundError: Detected background access to dialog manager. Please use background manager available via `manager.bg()` method to access methods from background tasks. Help PLS

**Comment by almaziphone** [comment]
dp = Dispatcher(bot, storage=storage)
Delete parametr run_tasks_by_default=True

**Comment by Tishka17** [comment]
I have no idea why there exists option `run_tasks_by_default`. 

Using middlewares you control where dependcies are initialized and where they are released. Background tasks are working outside of lifecycle of those dependencies, so you cannot use them (they can be released at that moment). 

That's what you exacltly see when you try to access dialog_manaer from background task: it is already released and so cannot be used in task.
