### ISSUE TITLE
How stop/hide/delete dialog/widget in telegram chat

### ISSUE THREAD

**Issue by Scubano** [Tishka17/aiogram_dialog#245]
Create and show dialog with method "start". After some action i want to hide/delete my window with const ans buttons. How can i do it?

**Comment by vlkorsakov** [comment]
This can only be done manually because aiogram-dialog does not support it due to Telegram's restrictions (2 days to delete message).

You can override the methods in DialogManager or MessageManager, but I am unable to provide any further assistance.

**Comment by Scubano** [comment]
but simple msg easy to del: msg.delete() may ba i am not understand what is widget

**Comment by vlkorsakov** [comment]
One window represents one message in a Telegram chat.

The message is composed of widgets, where a window acts as a container for widgets. Widgets are designed for reuse and are responsible for specific parts of the message, such as `StaticMedia` for videos or photos, and `Const` for static text. `Button` represents a single inline button.

To hide a widget, it can be assigned an argument when. For example, `Button(..., when=F["is_admin"])` would show the button only if the user is an admin.

**Comment by Scubano** [comment]
sorry for poor English
***
yes, i thought about when, but have not yet figured out how to implement dynamically when=True/False e.g. in response to a button click

**Comment by Scubano** [comment]
Или как сделать динамическое переключение when в одном окне при каком либо событии

**Comment by Tishka17** [comment]
Message, showing Dialog automatically refreshes after every processed event. `when` condition is checked again on every updated. So the only thing you need is to provide actual data from your `getter` function

**Comment by Tishka17** [comment]
https://aiogram-dialog.readthedocs.io/en/2.0.0/widgets/hiding/index.html
