### ISSUE TITLE
Changing the StatesGroup name with Redis enabled

### ISSUE THREAD

**Issue by WilliamQosmos** [Tishka17/aiogram_dialog#246]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: MacOS 13.2.1 (22D68)
* Python Version: 3.10
* aiogram version: 3.0.0b7
* aiogram-dialog version: 2.0.0b17

## Expected Behavior

If it is impossible to find a StatesGroup with this name, delete the library context from Redis if an error occurs

## Current Behavior

Any update that is not even related to dialogs crashes with an error: "aiogram_dialog.api.exceptions.UnknownState: Unknown state group"

## Failure Information (for bugs)

if Redis is running and connected to the storage in the manager, then when the StatesGroup name is changed, it is impossible to start the bot now until you completely clean the Redis

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Launching a bot with a StatesGroup named DialogSG
2. The user uses the dialogs
3. Changing the StatesGroup name to DialogMain
4. Restarting bot
5. The user has not yet used dialogs with StatesGroup named DialogMain
6. The aiogram_dialog context in Redis contains information about a StatesGroup named Dialog for this user
7. When processing any bot update, aiogram_dialog checks its context in Redis (aiogram_dialog.context.intent_middleware - DEBUG - Loading context for intent: `None`, stack: ``, user: `123456789`, chat: `-123456789`)
8. An error pops up "aiogram_dialog.api.exceptions.UnknownState: Unknown state group"

### Failure Logs

https://gist.github.com/WilliamQosmos/e6043ca04da66a49cc7a310781a8a703

**Comment by Tishka17** [comment]
please check this way of handling events:
https://github.com/Tishka17/aiogram_dialog/blob/develop/example/simple.py#L154

**Comment by WilliamQosmos** [comment]
This helped a lot, thanks for the reply
