### ISSUE TITLE
Can i dynamically create buttons or other objects in Window?

### ISSUE THREAD

**Issue by KonstantinKlepikov** [Tishka17/aiogram_dialog#247]
Something like that (is not real code, just idea):

```python
def get__buttons(buttons: list[Button]) -> Group:
        Group(
            *buttons,
            id="buttons",
            width=6,
                )

window = Window(
    Const('Awailable buttons:'),
    get_buttons,
    ...
)

main_dialog = Dialog(window)
# now register

# now call this kb in dialogue process and add buttoms dynamicaly
```

i need create some kind of buttons from dynamic data, f.e. that data is get from db as result of chat dialog

**Comment by Tishka17** [comment]
I recommends you to distinguish Button as a library widgets and InlineKeyboardButton as a telegram objects. 

In window you have predefined number of widgets, but:
1. one keyboard widget like `Button`  can produce multiple telegram buttons. One of such widgets is `Select`. Using one Select widget in window you get a set of smilar buttons representing list of items. They will have the same action, but it will get selected item id
2. widget can be hidden usign `when=` flag.

So probably for your case you need `Select`/`Radio`/`Multiselect`/`ListGroup`. If none of them fits your requirements you can create your own widget.
