### ISSUE TITLE
Сжимается видео на IOS

### ISSUE THREAD

**Issue by Mat0mba24** [Tishka17/aiogram_dialog#256]
**Использую StaticMedia с типом VIDEO.**

**На Android видео отображается нормально, как исходник:**
![image](https://user-images.githubusercontent.com/76114115/234790080-cc5dbafe-77a4-478a-b8cd-39152616a328.png)

**На IOS сжимается до квадратного:**
![image](https://user-images.githubusercontent.com/76114115/234790004-0eb9b826-1550-4b6f-92b8-3954238b9271.png)

**В чем может быть причина?**

**Comment by Baltasaruss** [comment]
Как вы решили проблему?
