### ISSUE TITLE
Ошибка NoContextError

### ISSUE THREAD

**Issue by LokiFarbauty** [Tishka17/aiogram_dialog#279]
async def name_handler(message: Message, message_input: MessageInput,
                       manager: DialogManager):
    if manager.is_preview():
        await manager.next()
        return
    manager.dialog_data["name"] = message.text
    await message.answer(f"Nice to meet you, {message.text}")
    #await manager.next()
    await manager.done()

В примере simple.py если заменить await manager.next() на await manager.done()
возникает ошибка NoContextError

**Comment by LokiFarbauty** [comment]
Как я понял ошибка возникает, что я пытаюсь завершить последний диалог?

**Comment by Tishka17** [comment]
If you are talking about 2.0b19, then it is a know error and fixed in beta20.
