### ISSUE TITLE
Removed menu

### ISSUE THREAD

**Issue by Krak3nDev** [Tishka17/aiogram_dialog#323]
Menu was removed, but i have error, because Redis. Need more normal error
![image](https://github.com/Tishka17/aiogram_dialog/assets/110890789/a80dad7d-2be6-467b-a418-9bcf7fb677f0)

**Comment by Tishka17** [comment]
You have `UnknownState` error. Isn't it enough?

**Comment by Krak3nDev** [comment]
closed
