### ISSUE TITLE
Bug: Issue with the find method in Widget Case

### ISSUE THREAD

**Issue by rahmatj0n** [Tishka17/aiogram_dialog#334]
I wanted to retrieve a checkbox widget, but the manager.find() method always returned -1. After debugging a bit, I discovered that the issue is related to the Case widget. It turns out that in the Case widget, the check is performed as shown in the image below. In the Case widget, you need to pass a dictionary with texts, and if the key in this dictionary is a string, the find() method of the string is called. This can result in unexpected behavior, making it impossible to retrieve the desired widget.
![Снимок экрана-20231111131841-1443x158](https://github.com/Tishka17/aiogram_dialog/assets/64601557/8d6dbdaf-f9f7-4a50-9907-15baecd5bbfc)

**Comment by Tishka17** [comment]
it is already fixed since 2.0.0b18

https://github.com/Tishka17/aiogram_dialog/commit/fff17f779e506b90a748c61b3d6238b843668f3a
