### ISSUE TITLE
Implementing Multiple Dynamic Counter Widgets with Text Parameters in aiogram-dialog

### ISSUE THREAD

**Issue by coumarin-geraniol** [Tishka17/aiogram_dialog#352]
I have a question regarding functionality: is it possible to implement the simultaneous creation of multiple Counter widgets in a window? For instance, I am sending data from db_products to the window via a getter, and I would like each product in this list to be displayed as a separate Counter widget dynamically. Would it also be possible to add a text parameter to each Counter, for example, product.name?

**Comment by Tishka17** [comment]
You can use ListGroup. See an example https://github.com/Tishka17/aiogram_dialog/blob/develop/example/list_group.py
Also you might need `ManagedListGroup.find_for_item` to access values.
