### ISSUE TITLE
Launching a dialog with the transmission of dynamic data for the status of the checkbox buttons

### ISSUE THREAD

**Issue by 24vgk** [Tishka17/aiogram_dialog#363]
Good afternoon! Please tell me, is it possible to set the values in the checkboxes not by default, but depending on the situation? Example: there is a table of 5 administrator options. Depending on which administrator we have selected for editing, its parameters are loaded, and the checkbox buttons should have the appropriate state. But how do I get there?

**Comment by Tishka17** [comment]
I see the 2 ways of dealing with this:

1. Immediate saving. If you want to store state of each button immediately to database, then you probably do not need checkboxes here. Just make several buttons and hide some of them using `when`. Or make the text of button dynamic using `when`

2. Loading on start and saving in the end of working with dialog. Then load data inside `on_start` dialog handler, call `set_checked` for all buttons. When user clicks "Save" or other action then get status of all checkboxes and save it to database.

So the main question here is whether you want to have temporary state of widgets (2nd option) or want them to show exactly what you have in DB (1st option).
