### ISSUE TITLE
Start calendar widget with scope Year

### ISSUE THREAD

**Issue by m-novitsky** [Tishka17/aiogram_dialog#369]
How can I make the starting view "Year" in the calendar? I believe set_scope, but how and where to apply this?

**Comment by Tishka17** [comment]
you can call `set_scope` on dialog startup or override `get_scope`. For the first option it will be like

```python
async def on_dialog_start(_, dialog_manager):
   dialog_manager.find("cal").set_scope(Scope.YEARS)

Dialog(
   Window(
     ...
     Calendar(id="cal",...),
    ...
   ),
   on_start=on_dialog_start,
)

```
