### ISSUE TITLE
Dynamic list of DynamicMedia

### ISSUE THREAD

**Issue by gavrilikhin-d** [Tishka17/aiogram_dialog#417]
How to show a list of DynamicMedia in dialog?

**Comment by Tishka17** [comment]
What do you mean? How this should be seen from user side?

Btw, telegram has very poor features with media albums, so they are not supported in dialogs

**Comment by gavrilikhin-d** [comment]
For example:
User uploads N photos
Dialog shows those N photos

**Comment by Tishka17** [comment]
No, media groups are not supported and won'tbe unless telegram changes them a lot
