### ISSUE TITLE
Start(data=)

### ISSUE THREAD

**Issue by NiaFoxter** [Tishka17/aiogram_dialog#419]
Как именно работает передача данных через виджет Start?
То есть, если это в функции, я могу просто сослаться с dialog_manager(а) или прикрутить данные, которые фигурируют в этой функции
`await dialog_manager.start(Some.State, data=dialog_manager.dialog_data["user_input"]`
Но как мне получить доступ к данным через виджет?
`        Start(
            Const("some text"),
            id="some_id",
            state=Some.State,
            data=(?),
        ),
`
dialog_manager, dialog_data подчеркивает
Просто data тоже не понятное
Подскажите, а то в примерах, вроде как, нету

**Comment by Tishka17** [comment]
`dialog_manager.start_data`

**Comment by NiaFoxter** [comment]
Прошу прощения, возможно мой вопрос был не совсем коректно задан
Насколько я понимаю, с помощью  `dialog_manager.start_data` я могу достать данные, которые были переданы с другого диалога.
Но у меня не получается их передать с помощью виджета Start
![image](https://github.com/user-attachments/assets/e5031f22-3056-40f5-a505-22d4287501dc)

**Comment by Tishka17** [comment]
Виджет start может передать только фиксированные данные. Если нужна какая-то дианмика - вы можете вызвать dialog_manager.start() из обычного обработчика в Button

**Comment by NiaFoxter** [comment]
Жаль. Благодарю
