### ISSUE TITLE
Nested radio buttons

### ISSUE THREAD

**Issue by KapKapkin** [Tishka17/aiogram_dialog#430]
It is possible to nest Radio in ListGroup? For example, getter creates dict with `{"properties" : [[choice11, choice12...] ,  [choice21, choice22...]]}`. In this case I need 2 radios, the first one will have a choice of `[choice11, choice12...]`, the second one `[choice21, choice22...]`. Number of lists like `[choice11, choice12...]` is unknown.

**Comment by Tishka17** [comment]
I'd say you need something to identify elements of top level list for ListGroup logic, the rest is pretty straight forward. So, yes, you can put radio into ListGroup

**Comment by Tishka17** [comment]
I guess the question was answered
