### ISSUE TITLE
How to display multiple photos in window

### ISSUE THREAD

**Issue by zax2002** [Tishka17/aiogram_dialog#455]
One of my windows should show text, action buttons, and a few photos with instructions. I don't see any built-in capability for aiogram_dialog to display a window consisting of multiple messages, and due to the limitation of telegram, only a single Media in a message is supported

I just used `send_media_group` in `on_click` on `SwitchTo` from the previous window to send photos. It works, but it's very ugly, and after switching to another window, the photo remains in the chat, which I don't like. I managed to save sent messages with photos to `dialog_data` and then get them and delete in every callback that leads the user out of my photo window

Is there any better solution to this problem using your library?

Maybe I can add a callback somewhere for entering and exiting a specific window to send and delete photos there? So that all the logic related to these photos belongs to the target window

**Comment by Tishka17** [comment]
I cannot suggest much here. I have this example https://github.com/Tishka17/aiogram_dialog/blob/develop/example/input_media_group.py and `MediaScroll` widget

**Comment by zax2002** [comment]
Thanks
