### ISSUE TITLE
aiogram 3.0 support

### ISSUE THREAD

**Issue by Tishka17** [Tishka17/aiogram_dialog#57]

**Comment by Tishka17** [comment]
TODO:
* [ ] Fix storage usage
* [ ] Fix `event.Config.allow_mutation = True`
* [ ] Check if `remove_kbd` properly used
* [ ] simplify `detect_content_type`
* [ ] fix aiogram locks with custom event

**Comment by darksidecat** [comment]
- [ ] DialogRegistry init, check that `dp` is `Dispatcher`, not `Router`
- [ ] Conversation: add 'aiogd_update' observer in `Dispatcher`, [ref](https://github.com/darksidecat/aiogram_dialog/tree/aiogram3-dev-aiogd-event-dp)
- [ ] Conversation: Middleware registation for `Update` or `Update.update_type`\`s

**Comment by darksidecat** [comment]
> * [ ]  fix aiogram locks with custom event

Maybe add new middleware for aiogd_update that will be aquire lock for user/chat key and register it before other middlewares? Like in aiogram

**Comment by darksidecat** [comment]
> * simplify `detect_content_type`

[Upstream PR](https://github.com/aiogram/aiogram/pull/669)

**Comment by Tishka17** [comment]
Closing this issue as it is merged to develop
