### ISSUE TITLE
Enhancement of ScrollingGroup 📜

### ISSUE THREAD

**Issue by Salz0** [Tishka17/aiogram_dialog#63]
Hey there 👋

Currently, the ScrollingGroup doesn't stop to scroll when it gets to the last page.

So instead of stopping and doing nothing, it scrolls through the same page "in-place". Whenever you want to go back --> you have to click the same amount of times.

Would be nice to have no scrolling as a default

**Comment by nacknime-official** [comment]
maybe duplicate of #59
