### ISSUE TITLE
Add Photo widget

### ISSUE THREAD

**Issue by mixartemev** [Tishka17/aiogram_dialog#64]
How about to add new widget Photo (to add photo in Window)?
Using like a:
<img width="628" src="https://user-images.githubusercontent.com/5181924/127773020-05abb639-8f34-42e5-8510-af876a0b01a4.png">

**Comment by Tishka17** [comment]
In telegram you cannot update message with photo to message without it. So currently I have no idea how to implements this feature correctly.

**Comment by mixartemev** [comment]
Hmm.. indeed:(

**Comment by mixartemev** [comment]
Wow! It finally works!🤩
