### ISSUE TITLE
[BUG] Inline mode.

### ISSUE THREAD

**Issue by Fom123** [Tishka17/aiogram_dialog#66]
If in an answer of inline mode(input_message_content), add the inline button (with registered dialogs), then when it is pressed, middleware will give the error.

```python
File "/home/*****/PycharmProjects/*****/venv/lib/python3.9/site-packages/aiogram_dialog/context/intent_filter.py", line 104, in on_pre_process_callback_query
    chat_id=event.message.chat.id,
AttributeError: 'NoneType' object has no attribute 'chat' 
```                                 
_**Temporary solution:**_
In `aiogram_dialog/context/intent_filter.py` in `on_pre_process_callback_query` add the following line
```python
chat_id=event.message.chat.id if hasattr(event, "chat") else ""
```

**Comment by Tishka17** [comment]
For inline messages we can use `inline_message_id` and user_id to edit it. But is has no chat
